### ISSUE TITLE
Code & Models

### ISSUE THREAD

**Issue by hxu105** [AkariAsai/ATTEMPT#2]
Hi, thanks for your great works. Could you help to share the code and models? I would like to reproduce the experiments. Many thanks!

**Comment by AkariAsai** [comment]
Sorry I overlooked this! Just finishing up my internship and I'll finally have time to work on this this week, and will release the code soon. 
Please feel free to send an email to me and I'll share the links in the mean time:
akari[at]cs.washington.edu

**Comment by AkariAsai** [comment]
The code and model checkpoints are now available. Thank you so much for your patience!
